apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: grantAll
rules:
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - secrets
  - configmaps
  - pods/log
  verbs:
  - create
  - list
  - watch
  - delete
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - create
  - list
  - watch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - create
  - list
  - watch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: grantAll-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grantAll
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
