apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: grantClusterAll
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - persistentvolumes
  - storageclasses
  - persistentvolumeclaims
  - replicationcontrollers
  - events
  verbs:
  - list
  - create
  - delete
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - list
  - create
  - delete
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: grantClusterAllBind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grantClusterAll
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
